name: MiaSkillpool
main: dev.timefiles.miaskillpool.MiaSkillpoolPlugin
version: ${version}
api-version: "1.21"
description: 用于测试 MiaHub 下载和生命周期管理的 Mia 插件。
author: Timefiles404
commands:
  mias:
    description: MiaSkillpool 命令。
    usage: /mias reload
    permission: miaskillpool.reload
permissions:
  miaskillpool.reload:
    description: 允许重载 MiaSkillpool。
    default: op
