name: MiaForge
main: dev.timefiles.miaforge.MiaForgePlugin
version: ${version}
api-version: "1.21"
description: 用于测试 MiaHub 下载和生命周期管理的 Mia 插件。
author: Timefiles404
commands:
  miaf:
    description: MiaForge 命令。
    usage: /miaf reload
    permission: miaforge.reload
permissions:
  miaforge.reload:
    description: 允许重载 MiaForge。
    default: op
